# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-11 11:52
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Users', '0004_auto_20180307_1520'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='phone_number',
            field=models.CharField(max_length=17, validators=[django.core.validators.RegexValidator(message="Telefon numarası formatı şu şekilde olmalıdır: '05xx xxx xxxx'.", regex='^(05(\\d{2}) (\\d{3}) (\\d{4}))$')], verbose_name='Phone Number'),
        ),
    ]
