# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-11 17:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Car', '0002_auto_20180311_1452'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
