# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2018-03-15 21:37
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('Park', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='park',
            name='users',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL, verbose_name='Users'),
        ),
    ]
